title: soriYang's GitHub ğŸ˜›ğŸ˜ƒğŸ˜ğŸ˜—ğŸ˜™ğŸ˜›ğŸ˜´ğŸ˜ŸğŸ˜¤
logo: ./2_1.png
description: Welcome! This is my frist GitHub page.
show_downloads: true

google_analytics:


theme: jekyll-theme-minimal

url: https://soriYang_.github.io/PoeticCodeForNature/
