title: Love creatingğŸ˜ğŸ˜˜ğŸ˜›ğŸ˜ƒğŸ˜ğŸ˜—ğŸ˜™ğŸ˜›ğŸ˜´ğŸ˜ŸğŸ˜¤
title.background: "#004a40"
logo: ./2_1.png
description: There's a so many things i can love.
google_analytics:
theme: jekyll-theme-minimal
url: https://soriYang.github.io/PoeticCodeForNature
