title: soriYang's GitHub ğŸ˜›ğŸ˜ƒğŸ˜ğŸ˜—ğŸ˜™ğŸ˜›ğŸ˜´ğŸ˜ŸğŸ˜¤
"title.background": "#002b36"
logo: ./2_1.png
description: This is my first GitHub page.
google_analytics:
theme: jekyll-theme-minimal
url: https://soriYang.github.io/PoeticCodeForNature
