title: soriYang's GitHub ğŸ˜›ğŸ˜ƒğŸ˜ğŸ˜—ğŸ˜™ğŸ˜›ğŸ˜´ğŸ˜ŸğŸ˜¤
logo: ./2_1.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
url: https://soriYang.github.io/PoeticCodeForNature
"background": "#073642" 
